#!/bin/bash

clear
cd /root
mv led-b860/bled /usr/bin/
mv led-b860/bledon /usr/bin/
chmod +x /usr/bin/bled
chmod +x /usr/bin/bledon

cd /root
touch /root/led
echo ok > /root/led
echo " Install selesai"
echo " ketik perintah : bled -s"
echo " Untuk stop LED Indicator"
sleep 2
bash bled -r
